Started to port a few things from Spectre to SpectreKit
patriksvensson/spectre-kit pull request #2
Opened 2024-07-14 18:52 UTC by migueldeicaza

Decided to do a few things this Sunday morning, I am trying to stick to your design and style.

2024-07-14 19:46 UTC, patriksvensson requested changes
Looks good to me! The only two things that need to be fixed are the TODO parts in `Segment.truncate`.

Also, don't hesitate to do things in a more "Swiftesque" way if you think of something. I'm trying to learn, and if there is a more idiomatic way of doing things than I've done so far, I'm happy to change it. Also, SpectreKit does not have to be a 1:1 representation of Spectre.Console, so feel free to be creative 🙂

2024-07-14 19:46 UTC, patriksvensson commented on Sources/SpectreKit/Rendering/Segments.swift
> +            fatalError("TODO: I think this should be empty")
I think we can return an empty segment here

2024-07-14 19:46 UTC, patriksvensson commented on Sources/SpectreKit/Rendering/Segments.swift
> +            fatalError("TODO")
I think we can return an empty segment here

2024-07-14 21:14 UTC, patriksvensson commented
@migueldeicaza FYI, I've merged proper cell calculation to main, so you might want to rebase.

2024-07-15 01:36 UTC, migueldeicaza commented
Thank you for your review and guidance Patrik!

2024-07-15 06:57 UTC, merged

2024-07-15 06:57 UTC, patriksvensson commented
Merged! Thank you for your contribution. Much appreciated! 👍